# Generated by Django 4.2.2 on 2023-06-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_alojamiento', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('condiciones_medicas', models.TextField(blank=True)),
                ('tipo_comida', models.CharField(blank=True, max_length=100)),
                ('horarios_alimentacion', models.CharField(blank=True, max_length=100)),
                ('servicios_adicionales', models.TextField(blank=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.propietario')),
            ],
        ),
    ]
